[project]
name = "list3-numericalcalculusufabc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "requirements-txt",
    "scipy>=1.15.2",
    "streamlit>=1.44.1",
]
